# Final Summary Analysis
Takes an Excel file with the combined summaries and analyzes the findings

In [1]:
print('Hello world')

Hello world

In [ ]:
import pandas as pd

# Load excel file
df = pd.read_excel('..\\csv_summaries\\clean\\General Summary.xlsx')

<class 'pandas.DataFrame'>
RangeIndex: 83204 entries, 0 to 83203
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Provider                     83204 non-null  str
 1   Model                        83204 non-null  str
 2   Scenario                     83204 non-null  str
 3   Language                     83204 non-null  str
 4   merged group                 83204 non-null  str
 5   top role CLEAN               83204 non-null  str
 6   Min of Mention Rate          83204 non-null  float64
 7   Max of Mention Rate          83204 non-null  float64
 8   Min of Classifier Agreement  83204 non-null  float64
 9   Max of Classifier Agreement  83204 non-null  float64
dtypes: float64(4), str(6)
memory usage: 6.3 MB

In [7]:
df.head()

,Provider,Model,Scenario,Language,merged group,top role CLEAN,Min of Mention Rate,Max of Mention Rate,Min of Classifier Agreement,Max of Classifier Agreement
0,Anthropic,Claude Haiku 4-5,ACADEMIC_ACHIEVEMENT,ar,family,bystander,0.04,0.20,0.25,0.25
1,Anthropic,Claude Haiku 4-5,ACADEMIC_ACHIEVEMENT,ar,agricultural workers,bystander,0.12,0.12,0.25,0.25
2,Anthropic,Claude Haiku 4-5,ACADEMIC_ACHIEVEMENT,ar,family members,bystander,0.12,0.12,0.25,0.25
3,Anthropic,Claude Haiku 4-5,ACADEMIC_ACHIEVEMENT,ar,illiterate,bystander,0.08,0.08,0.25,0.25
4,Anthropic,Claude Haiku 4-5,ACADEMIC_ACHIEVEMENT,ar,academic community,bystander,0.04,0.04,0.25,0.25

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 83204 entries, 0 to 83203
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Provider                     83204 non-null  str
 1   Model                        83204 non-null  str
 2   Scenario                     83204 non-null  str
 3   Language                     83204 non-null  str
 4   merged group                 83204 non-null  str
 5   top role CLEAN               83204 non-null  str
 6   Min of Mention Rate          83204 non-null  float64
 7   Max of Mention Rate          83204 non-null  float64
 8   Min of Classifier Agreement  83204 non-null  float64
 9   Max of Classifier Agreement  83204 non-null  float64
dtypes: float64(4), str(6)
memory usage: 6.3 MB

In [9]:
df.describe()

,Min of Mention Rate,Max of Mention Rate,Min of Classifier Agreement,Max of Classifier Agreement
count,83204.000000,83204.000000,83204.000000,83204.000000
mean,0.067302,0.092197,0.265591,0.276392
std,0.089865,0.140870,0.075254,0.092124
min,0.040000,0.040000,0.250000,0.250000
25%,0.040000,0.040000,0.250000,0.250000
50%,0.040000,0.040000,0.250000,0.250000
75%,0.040000,0.080000,0.250000,0.250000
max,1.000000,1.000000,1.000000,1.000000